Issue#4753
wixtoolset/Core pull request #214
Opened 2021-01-22 19:38 UTC by cpuwzd

I have researched all aspects of this change, and believe it to be sound. I don't think there were any stylistic issues over which I
might have stumbled, but please let me know if I missed anything.

I've had more trouble interacting with git than with the Wix code. Please accept this as my first pull request.

The following comments are from Compiler_2.cs, line 1580 et. seq, and should presumably be removed before merging:

                        // Issue #4753
                        // Unlike file paths, registry paths are not allowed to start or end with a backslash.
                        // Unless run as an administrator (i.e. with elevated privileges), keys that violate
                        // this rule results in ICE03 compiler errors. (Registry paths are not pre-evaluated
                        // when running with elevated privileges.) Since many users include trailing backslashes
                        // in registry paths, we are silently correcting this error here. If there are multiple
                        // trailing slashes, removing the final one, as done here, will purposely still generate
                        // the ICE03 error.

Ron Martin

2021-01-22 21:06 UTC, robmen requested changes
In the commit message for the change, end the message with `Fixes wixtoolset/issues#4753` and GitHub will automatically link the PR and close the issue in one go. Spiffy GitHub feature.

2021-01-22 21:06 UTC, robmen commented on src/WixToolset.Core/Compiler_2.cs
> +                        // the ICE03 error.
We don't include issue fixes and comments in the code itself. This block of text would be great text to put in the git commit message.

2021-01-22 21:06 UTC, robmen commented on src/WixToolset.Core/Compiler_2.cs
> +                        if (null != key && key.EndsWith(@"\"))
I think you can simplify all of this with `key?.TrimEnd('\\');`

2021-01-22 21:06 UTC, robmen commented on src/WixToolset.Core/Compiler_2.cs
>                          break;
I think the following needs to be above the `break;` statement to work.

2021-01-22 21:08 UTC, rseanhall commented
> In the commit message for the change, end the message with Fixes wixtoolset/issues#4753 and GitHub will automatically link the PR and close the issue in one go.

@robmen I've been meaning to ask you about that. It links the commit with the issue, but not the PR with the issue. I would prefer that message goes in the PR.

2021-01-22 21:14 UTC, robmen commented
@rseanhall that's unfortunate because I really want the `Fixed` line in the commit message, which means the information needs to be duplicated.

2021-01-22 21:19 UTC, rseanhall commented
What GitHub functionality do you want from putting it in the commit message? Do you like seeing all the commits when you look at an issue like https://github.com/wixtoolset/issues/issues/6245? Would it be ok to just put `Fixed #4753` in the commit message, even though that won't actually trigger any GitHub functionality (since the issues are in a different repo)?

2021-01-22 21:23 UTC, robmen commented
> What GitHub functionality do you want from putting it in the commit message?

Not GitHub but I want to know the issue fixed in a commit without having to find the PR that goes with the commit.

> Would it be ok to just put `Fixed #4753` in the commit message, even though that won't actually trigger any GitHub functionality (since the issues are in a different repo)?

That would be sufficient but I'd use the GitHub syntax so I don't have to remember. :smile:

2021-01-22 21:26 UTC, rseanhall commented
> That would be sufficient but I'd use the GitHub syntax so I don't have to remember.

My biggest problem with the GitHub syntax is that for cross-repo work, the first one will close the issue. Plus I find all the commit links in the issue annoying.

2021-01-22 21:28 UTC, rseanhall commented on src/WixToolset.Core/Compiler_2.cs
> +                        if (null != key && key.EndsWith(@"\"))
@robmen You realize that changes the behavior right? That would remove all trailing slashes.

2021-01-22 21:34 UTC, robmen commented on src/WixToolset.Core/Compiler_2.cs
> +                        if (null != key && key.EndsWith(@"\"))
Of course. If we think it's important to leave a single trailing slash if the user added any, then the code would be more complicated (but trimming a single `\` doesn't seem sufficient to fix the error).

2021-01-22 23:09 UTC, cpuwzd commented on src/WixToolset.Core/Compiler_2.cs
> +                        // the ICE03 error.
Rob,
Quoting from my pull request, "The following comments are from Compiler_2.cs, line 1580 et. seq, and should presumably be removed before merging:". I knew you wouldn't want these comments in the code, but I didn't want them to get lost while I was fighting with multiple local repositories for the same remote repository.
In which commit would you like them, now that I have amended the pull request and need to do so again?

2021-01-22 23:11 UTC, robmen commented on src/WixToolset.Core/Compiler_2.cs
> +                        // the ICE03 error.
This change is small enough that I think you'll only need one commit. So you can squash them all down into one and use this very nice text as the commit message.

2021-01-23 00:08 UTC, cpuwzd commented on src/WixToolset.Core/Compiler_2.cs
> +                        if (null != key && key.EndsWith(@"\"))
Registry paths are unlike file paths. They are neither supposed to begin nor end with any backslashes. A single backslash by itself is not a valid registry path. In the original Win32 registry API, there were no paths at all. Each segment required that another node be opened. However, the tag/value pairs were associated with each node. An extra backslash between two nodes is clearly nonsense, because it implies a nameless node with no means of navigation. Wix 3 gives errors in this situation. A leading or trailing backslash also implies a nameless node and should also be flagged as an error. I'm not sure who started the push to allow a trailing backslash, but I think it is wrong-headed. If we're conceding to ignorance or laziness, then more than one trailing backslash should still be considered an error, as it is in a file path. I think the issue comes down to the point at which the error is detected and reported. You don't want it to float too far downstream where it might cause a higher-level error that is more confusing, and you certainly don't want it to be a run-time error when an installer is running.
What's behind not checking registry path validity at all when the Wix compiler is running at elevated privilege? This would just seem to push more errors downstream.

2021-01-23 00:13 UTC, cpuwzd commented on src/WixToolset.Core/Compiler_2.cs
>                          break;
I realized that I had cut my code and pasted it a line too high while I was dealing with multiple instances of my local repo. I had it fixed before you noticed my pull request. My apologies for not re-running my tests afterward.

2021-01-23 01:08 UTC, cpuwzd commented
I still can't build Core on my computer in release mode. I get the following error:

4>C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file 'D:\Repos\Wix\Core\build\obj\WixToolset.Core.WindowsInstaller\project.assets.json' doesn't have a target for <framework>. Ensure that restore has run and that you have included  <framework> in the TargetFrameworks for your project.

In slightly simplified terms, <framework> is one of

- net461
- net472 

  and the relevant projects are:

- WixToolset.Core.csproj
- WixToolset.Core.Burn.csproj
- WixToolset.Core.ExtensionCache.csproj
- WixToolset.Core.TestPackage.csproj
- WixToolset.Core.WindowsInstaller.csproj

In contrast, appveyor.cmd runs without error.

I'm going to see if I can find the file where I noticed that the net461 and net472 targets were commented out in release mode.

2021-01-23 01:13 UTC, rseanhall commented
If you're in Visual Studio and you switch from Debug to Release, you must close the solution because VS does not support the way we are building different frameworks. After reopening the solution, it should work.

2021-02-05 05:48 UTC, robmen commented
Obsoleted by #220

2021-02-05 05:48 UTC, closed without merging