#4008 - Allow packages and payloads over 2GiB
wixtoolset/Core pull request #228
Opened 2021-02-15 23:35 UTC by AlexKubiesa

This should resolve wixtoolset/issues/issues/4008.

The fix itself was simple - just converting an int to a long.

For the test, I basically copied the existing pattern in `BundleFixture`. The data file `large_file.dat` committed to the repo is a dummy file which gets enlarged to 2.5GiB during the test. It then gets deleted at the end of the test to avoid taking up a lot of space.

2021-02-15 23:42 UTC, robmen requested changes

2021-02-15 23:42 UTC, robmen commented on src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
> +    <None Remove="TestData\LargePayload\Bundle.en-us.wxl" />
This block is an artifact of adding files via VS, you don't need it.

2021-02-15 23:42 UTC, robmen commented on src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
> +                    Assert.Equal("1.0.0.0", bundleSymbol.Version);
Do we need to validate all these pieces of information? Most of it is covered by other targeted tests. It'd be best if this one focuses on the large file facets.

2021-02-15 23:42 UTC, robmen commented on src/test/WixToolsetTest.CoreIntegration/TestData/LargePayload/data/large_file.dat
> +When running the tests, this file will be overwritten with 2.5GB of data to test how Wix handles large files. We've avoided
But this file will always end up "edited" in git after a test run, correct? So, would be easy for someone (else) to accidentally commit the file. Probably better not to put the file in the repository or make sure it's ignored.

2021-02-15 23:44 UTC, AlexKubiesa commented on src/test/WixToolsetTest.CoreIntegration/TestData/LargePayload/data/large_file.dat
> +When running the tests, this file will be overwritten with 2.5GB of data to test how Wix handles large files. We've avoided
The file is only edited in the build output directory. The source file is left alone.

2021-02-16 00:26 UTC, robmen commented
One last nit: could you rebase these changes down to a single commit? I prefer to see the change and its test(s) all together in the same commit for future reference. Also, the separate commits for review feedback add noise to the history. Thanks.

PS: Sorry, should have mentioned that in last review.

2021-02-16 00:27 UTC, AlexKubiesa commented
Ok no worries, I'll do that now.

2021-02-16 00:36 UTC, robmen approved these changes

2021-02-16 00:39 UTC, merged

2021-02-16 18:17 UTC, rseanhall commented on src/test/WixToolsetTest.CoreIntegration/TestData/LargePayload/data/fakeba.dll
> +This is a fakeba.dll
@robmen Like you wanted them to narrow what was being tested, I would like tests not to have their own files unless it's necessary. Creating fake BA dlls and using localization seems like overkill in most scenarios and will also bloat the repo.

2021-02-16 18:18 UTC, robmen commented on src/test/WixToolsetTest.CoreIntegration/TestData/LargePayload/data/fakeba.dll
> +This is a fakeba.dll
I don't disagree but we should clean up all the tests to work this way.

2021-02-16 18:20 UTC, rseanhall commented on src/test/WixToolsetTest.CoreIntegration/TestData/LargePayload/data/fakeba.dll
> +This is a fakeba.dll
I already write all of my tests that way, I haven't looked lately at how many need to be cleaned up.