Fix WixVariable resolution for paths
wixtoolset/Core pull request #236
Opened 2021-03-04 00:16 UTC by drolevar

WixVariable resolution for paths wasn't working properly when linking with Wix library containing an embedded file.
The classic example is when it's necessary to override ThemeFile and LocalizationFile in WixStandardBootstrapperApplication.
Despite that new files were specified the ones embedded into the wixlib were used.

2021-03-04 08:33 UTC, robmen requested changes
This'll probably require a bit more structural changes, so I understand if you don't want to tackle this scale of issue and I'll pick it up. :)

2021-03-04 08:33 UTC, robmen commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +            if (!resolution.UpdatedValue && field.PreviousValue != null)
I don't think the solution is for the `ResolveFieldsCommand` to always re-resolve a field if nothing was updated. In v3, libraries only resolved object fields when binding files. I think the fix is to bring that behavior back in v4. That'll probably require a bit more structural changes, so I understand if you don't want to tackle this scale of issue and I'll pick it up. :)

2021-03-04 09:07 UTC, drolevar commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +            if (!resolution.UpdatedValue && field.PreviousValue != null)
@robmen I also would think it's a more logical thing to do. It's just there was already infrastructure for that but it was removed in this commit: wixtoolset/Core@9c714a8. I thought there was some architectural thought behind that. Also WixOutput class apparently had constructor parameter accepting the list of embedded files (I saw a dangling XML comment somewhere).
But you can pick it up (after I implement your suggestions) and I can research on how to bring back the 3.0 behaviour.

2021-03-04 09:23 UTC, robmen commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +            if (!resolution.UpdatedValue && field.PreviousValue != null)
Yeah, that's the code I was thinking of in the librarian (but looking in the wrong place before) so there is (possibly) less structural change than I feared. I don't remember off the top of my head how v3 was handling this scenario. We probably just broke it somewhere along the way.

At the very least, adding a `Skip`ped unit test showing the problem, is *extremely * helpful tracking down the root cause later.

2021-03-04 10:02 UTC, drolevar commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +            if (!resolution.UpdatedValue && field.PreviousValue != null)
@robmen In v3 WixVariable value was not resolved at all in the librarian, but a `CabinetFileId` attribute was set on the field to indicate that there's an embedded file available.
Wix4 used to have `EmbeddedFileIndex` property for the same purpose, which has been replaced by `Embed` property which is just a bool. So if librarian doesn't resolve the variables there will be no way to relate it to the embedded file without further changes.

2021-03-04 15:50 UTC, robmen commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +            if (!resolution.UpdatedValue && field.PreviousValue != null)
Thanks, @drolevar, that's totally it. Great sleuthing. As I tried to simplify the handling of embedded binaries (which was an absolute mess of interdependencies), I can see how I lost this feature by attempting to re-use the source path.

Thank you for capturing the problem in wixtoolset/issues#6376

2021-03-04 15:53 UTC, robmen requested changes
Could we change this PR (or open a new PR if you don't want to lose the solution) into just the unit test fix and add the `Skip` to the test referencing the open bug. The unit test helps me see exactly how to reproduce the problem and I'll go back and re-think the current design based on the feature lost here.

Okay?

2021-03-04 15:53 UTC, robmen commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +                            if (fieldType == IntermediateFieldType.String || fieldType == IntermediateFieldType.Path)
I'm pretty confident we don't want to re-resolve all path fields that happen to have a `PreviousValue`.

2021-03-04 16:44 UTC, drolevar commented on src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
> +                            if (fieldType == IntermediateFieldType.String || fieldType == IntermediateFieldType.Path)
@robmen Created new PR #237

2021-03-26 13:35 UTC, rseanhall commented
This was fixed differently in https://github.com/wixtoolset/Core/pull/256.

2021-03-26 13:35 UTC, closed without merging