Create unit test for WixVariable resolution issue #6376
wixtoolset/Core pull request #237
Opened 2021-03-04 16:39 UTC by drolevar

Created a unit test for WixVariable resolution issue wixtoolset/issues#6376

2021-03-04 21:09 UTC, robmen requested changes

2021-03-04 21:09 UTC, robmen commented on src/test/WixToolsetTest.CoreIntegration/TestData/SingleFile/PackageComponents.wxs
> +        <Binary Id="Test.txt" SourceFile="!(wix.TestFile=test.txt)" />
This test file is shared with many tests. We should isolate this scenario to a single (or the minimal) test case. That should dalso fix the build break.

2021-03-05 12:37 UTC, drolevar commented on src/test/WixToolsetTest.CoreIntegration/TestData/SingleFile/PackageComponents.wxs
> +        <Binary Id="Test.txt" SourceFile="!(wix.TestFile=test.txt)" />
Done

2021-03-05 15:38 UTC, merged

2021-03-05 15:39 UTC, robmen commented
Thank you.